src/web/Controllers/GroupsController.cs
using AAE.GGTool.Services;
using AAE.GGTool.Web.Authorization;
using AAE.GGTool.Web.Helpers.Vue;
using AAE.GGTool.Web.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AAE.GGTool.Web.Controllers
{
    [Route("g")]
    public class GroupsController : Controller
    {
        private readonly IVueParser _vueParser;
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        public GroupsController(IVueParser vueParser, IMapper mapper, IGroupService groupService)
        {
            _vueParser = vueParser ?? throw new ArgumentNullException(nameof(vueParser));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
        }

        [HttpGet("{group}")]
        public async Task<IActionResult> Index(string group, [FromQuery(Name = "refresh")] bool forceRefresh)
        {
            var groupObj = await _groupService.GetAsync(string.Join("@", group, ViewBag.AppConfig.GroupDomain), forceRefresh);

            var vm = new GroupDetailViewModel()
            {
                Group = groupObj
            };

            vm.VueData = _vueParser.ParseData(vm);

            return View(vm);
        }

        [HttpGet("add")]
        [PermissionAuthorize(Permissions.CreateGroup)]
        public IActionResult Add()
        {
            return View();
        }
    }
}

src/web/Controllers/HomeController.cs
using System;
using System.Threading.Tasks;
using AAE.GGTool.Services;
using AAE.GGTool.Web.Helpers.Vue;
using AAE.GGTool.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using UW.Services.Ldap;

namespace AAE.GGTool.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGroupService _groupService;
        private readonly IVueParser _vueParser;
        //private readonly IUWLdapClient _ldapClient;

        public HomeController(IGroupService groupService, IVueParser vueParser)
        {
            _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
            _vueParser = vueParser;
        }

        public async Task<IActionResult> Index()
        {
            var groups = await _groupService.ListAsync();

            var vm = new GroupsListViewModel()
            {
                Groups = groups,
                AppId = ViewBag.AppConfig.UWAPIAppId
            };

            vm.VueData = _vueParser.ParseData(vm);

            return View(vm);
        }

        //public async Task<IActionResult> Test()
        //{
        //    var result = await _ldapClient.SearchAsync("eric dieckman");

        //    return Ok(result);
        //}
    }
}

src/web/Controllers/MembersController.cs
using AAE.GGTool.Services;
using AAE.GGTool.Web.Authorization;
using AAE.GGTool.Web.Helpers.Vue;
using AAE.GGTool.Web.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AAE.GGTool.Web.Controllers
{
    public class MembersController : Controller
    {
        private readonly IGroupMemberService _groupMemberService;
        private readonly IGroupService _groupService;

        private readonly IVueParser _vueParser;
        private readonly IMapper _mapper;

        public MembersController(IGroupMemberService groupMemberService, IVueParser vueParser, IMapper mapper, IGroupService groupService)
        {
            _vueParser = vueParser ?? throw new ArgumentNullException(nameof(vueParser));
            _groupMemberService = groupMemberService ?? throw new ArgumentNullException(nameof(groupMemberService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
        }

        // GET /aae-faculty/members
        [HttpGet("g/{group}/members")]
        public async Task<IActionResult> Index(string group)
        {
            var groupEmail = string.Join("@", group, ViewBag.AppConfig.GroupDomain);

            var groupTask = _groupService.GetAsync(groupEmail);

            var membersTask = _groupMemberService.GetAllAsync(groupEmail);

            await Task.WhenAll(groupTask, membersTask);

            var vm = new MemberListViewModel()
            {
                GroupName = groupTask.Result.Name,
                GroupEmail = groupTask.Result.Email,
                GroupDescription = groupTask.Result.Description,
                Members = membersTask.Result
            };

            vm.VueData = _vueParser.ParseData(vm);

            return View(vm);
        }

        // GET /search
        [HttpGet("search")]
        public IActionResult Search()
        {
            return View();
        }

        [PermissionAuthorize(Permissions.EditGroupMembership)]
        [HttpGet("members/addmultiple")]
        public async Task<IActionResult> AddMultiple()
        {
            var groups = await _groupService.ListAsync();
            var vm = new MultiAddViewModel()
            {
                Groups = groups
            };

            vm.VueData = _vueParser.ParseData(vm);
            return View(vm);
        }
    }
}

src/web/Views/Home/Index.cshtml
@model GroupsListViewModel
@{
    ViewData["Title"] = "";
}
@section breadcrumbs {

}
<div class="mt-2">
    <h2>Groups</h2>
    Authorized for @Model.AppId

</div>
<div class="mt-3">

    <table class="table table-sm">
        <thead>
            <tr>
                <th>List</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var group in Model.Groups)
            {
                <tr>
                    <td>
                        <a  asp-controller="Members" asp-action="Index" asp-route-group="@group.Split("@")[0]" class="list-group-item list-group-item-action"
                           title="Edit Members in GGTool">@group</a>
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Members" asp-action="Index" asp-route-group="@group.Split("@")[0]" title="Edit Members in GGTool"><i class="fas fa-users"></i></a>
                        <a class="btn btn-dark" asp-controller="Groups" asp-action="Index" asp-route-group="@group.Split("@")[0]"
                           title="Edit Settings in GGTool"><i class="fas fa-cog"></i></a>
                        <div class="btn-group">
                            <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown">
                                <i class="fab fa-google"></i>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="https://groups.google.com/u/1/a/@group.Split("@")[1]/g/@group.Split("@")[0]/members"
                                       target="_blank"
                                       class="dropdown-item"
                                       title="Edit Members in Google Workspace"><i class="fab fa-google"></i> <i class="fas fa-users"></i> Members</a>
                                </li>
                                <li>
                                    <a href="https://groups.google.com/u/1/a/@group.Split("@")[1]/g/@group.Split("@")[0]/settings"
                                       target="_blank"
                                       class="dropdown-item"
                                       title="Edit Settings in Google Workspace"><i class="fab fa-google"></i> <i class="fas fa-cog"></i> Settings</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

@section mastercss 

{
<style type="text/css">
    .list-group-item {
        padding: .5rem;
    }
</style>
}