src/web/Controllers/AboutController.cs
using System.Threading.Tasks;
using AAE.GGTool.Web.ViewModels;
using GitLabApiClient;
using Microsoft.AspNetCore.Mvc;

namespace AAE.GGTool.Web.Controllers
{
    [Route("about")]
    public class AboutController : Controller
    {
        private readonly IGitLabClient _gitLabClient;
        public AboutController(IGitLabClient gitLabClient)
        {
            _gitLabClient = gitLabClient;
        }
        public async Task<IActionResult> Index()
        {
            var releases = await _gitLabClient.Releases.GetAsync("apps/ggtool");
            var vm = new AboutIndexViewModel()
            {
                Releases = releases
            };
            //return Ok(releases);
            return View(vm);
        }
    }
}

src/web/Views/Shared/Components/MainMenu/MainMenuViewComponent.cs
using System;
using System.Threading.Tasks;
using Aae.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AAE.GGTool.Web.Shared.Components.MainMenu
{
    public class MainMenuViewComponent : ViewComponent
    {
        private readonly IHttpContextAccessor _contextAccessor;
        public MainMenuViewComponent(IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor ?? throw new ArgumentNullException(nameof(contextAccessor));
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // // EXAMPLE below if using an app-specific identity rather than the original/standard
            // var user = new CCLogUser(_contextAccessor.HttpContext.User.Identities.Where(i=>i.AuthenticationType == ThisAppUser.ThisAppAuthenticationType).FirstOrDefault());
            var user = new ClaimsApplicationUser(_contextAccessor.HttpContext.User);

            // wrapping it in an async call until there is something that actually async (like a DB call)
            return await Task.Run(() =>
            {
                var vm = new ViewModels.MainMenu()
                {
                    LoggedInUser = $"{user.FirstName} {user.LastName}"
                };

                return View(vm);
            });
        }
    }
}

src/web/Views/Shared/_FavIcons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/img/favicon/favicon-16x16.png">
<link rel="manifest" href="~/img/favicon/site.webmanifest">
<link rel="mask-icon" href="~/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="~/img/favicon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="~/img/favicon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

src/web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @await Html.PartialAsync("_Favicons")
    <title>@(string.IsNullOrEmpty(ViewBag.Title) ? "" : ViewBag.Title + " - ")@ViewBag.AppConfig.Branding</title>
    <environment exclude="Development">
        <link asp-href-include="~/assets/style.*.css" rel="stylesheet" media="all"  />
    </environment>
    @RenderSection("mastercss", required: false)
</head>
<body>


    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container d-flex justify-content-between">
            <a class="navbar-brand" href="~/">
                <img src="~/img/ggtool-logo.png" alt="GGTool" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbars">
                @await Component.InvokeAsync("MainMenu")
            </div>
        </div>
    </nav>


    @if (!(ViewContext.RouteData.Values["controller"].ToString() == "Home" && ViewContext.RouteData.Values["action"].ToString() == "Index"))
    {
        <nav aria-label="breadcrumb" class="container mt-2">

            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="~/">Home</a></li>
                @RenderSection("breadcrumbs", required: false)
            </ol>
        </nav>
    }
    else {
        IgnoreSection("breadcrumbs");
    }






    <div class="container">
        @RenderBody()
    </div>
    <!-- /.container -->

    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; Copyright @DateTime.Now.Year, AAE IT Services Center - <a asp-action="Index" asp-controller="About">@ViewBag.AppConfig.Branding</a></p>
    </footer>

    <div id="layout_vue"></div>

    <environment exclude="Development">
        <script defer type="module" asp-src-include="~/assets/main.*.js"></script>
    </environment>

    <environment include="Development">
        <script defer type="module" src="~/@@vite/client"></script>
        <script defer type="module" src="~/pages/main.js"></script>
    </environment>

    @RenderSection("masterjs", required: false)
</body>
</html>