src/web/Controllers/Api/GroupsApiController.cs
using Aae.Authentication;
using AAE.GGTool.Services;
using AAE.GGTool.Web.Authorization;
using AAE.GGTool.Web.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Uw.GoogleGroups.Client;

namespace AAE.GGTool.Web.Controllers.Api;

[Route("api/groups")]
[ApiController]
public class GroupsApiController : Controller
{
    private readonly IGroupService _groupService;
    private readonly IGroupDefaultsService _groupDefaultsService;
    private readonly IGroupMemberService _groupMemberService;
    private readonly IMapper _mapper;

    public GroupsApiController(IGroupService groupService, IGroupDefaultsService groupDefaultsService, IMapper mapper, IGroupMemberService groupMemberService)
    {
        _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
        _groupDefaultsService = groupDefaultsService ?? throw new ArgumentNullException(nameof(groupDefaultsService));
        _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        _groupMemberService = groupMemberService ?? throw new ArgumentNullException(nameof(groupMemberService));
    }

    // POST /api/groups
    [PermissionAuthorize(Permissions.CreateGroup)]
    [HttpPost]
    public async Task<IActionResult> AddGroup(AddGroupViewModel group)
    {
        // create the new group to add using input data
        var groupToAdd = new Group()
        {
            Email = string.Join("@", group.Email, ViewBag.AppConfig.GroupDomain),
            Name = group.Name,
            Description = group.Description
        };

        // populate default settings
        var defaultSettings = await _groupDefaultsService.GetAsync(1001);
        _mapper.Map(defaultSettings.Defaults, groupToAdd);

        try
        {
            var groupFromGoogle = await _groupService.AddAsync(groupToAdd);

            // now add current user as an Owner
            var currentUser = new ClaimsApplicationUser(HttpContext.User);

            var memberToAdd = new Member()
            {
                Email = currentUser.Email,
                DeliverySettings = GoogleGroupConstants.DeliverySettings.NoEmail,
                Role = GoogleGroupConstants.Role.Owner
            };

            await _groupMemberService.AddOrUpdateAsync(groupFromGoogle.Email, memberToAdd);

            return Ok(groupFromGoogle);
        }
        catch (Exception ex)
        {
            var result = StatusCode(StatusCodes.Status500InternalServerError, new { ex.Message });
            return result;
        }
    }

    // GET /api/groups/aae-faculty
    [HttpGet("{group}")]
    public async Task<IActionResult> Get(string group, [FromQuery(Name = "refresh")] bool forceRefresh)
    {
        var result = await _groupService.GetAsync(string.Join("@", group, ViewBag.AppConfig.GroupDomain), forceRefresh);

        return Ok(result);
    }

    [PermissionAuthorize(Permissions.EditGroup)]
    [HttpPut("{group}")]
    public async Task<IActionResult> Update(string group, Group groupData)
    {
        groupData.Email = string.Join("@", group, ViewBag.AppConfig.GroupDomain);

        var result = await _groupService.UpdateAsync(groupData);

        return Ok(result);
    }

    [PermissionAuthorize(Permissions.DeleteGroup)]
    [HttpDelete("{group}")]
    public async Task<IActionResult> Delete(string group)
    {
        var groupEmail = string.Join("@", group, ViewBag.AppConfig.GroupDomain);
        await _groupService.DeleteAsync(groupEmail);

        return Ok();
    }
}

src/web/Controllers/GroupsController.cs
using AAE.GGTool.Services;
using AAE.GGTool.Web.Authorization;
using AAE.GGTool.Web.Helpers.Vue;
using AAE.GGTool.Web.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AAE.GGTool.Web.Controllers
{
    [Route("g")]
    public class GroupsController : Controller
    {
        private readonly IVueParser _vueParser;
        private readonly IMapper _mapper;
        private readonly IGroupService _groupService;
        public GroupsController(IVueParser vueParser, IMapper mapper, IGroupService groupService)
        {
            _vueParser = vueParser ?? throw new ArgumentNullException(nameof(vueParser));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _groupService = groupService ?? throw new ArgumentNullException(nameof(groupService));
        }

        [HttpGet("{group}")]
        public async Task<IActionResult> Index(string group, [FromQuery(Name = "refresh")] bool forceRefresh)
        {
            var groupObj = await _groupService.GetAsync(string.Join("@", group, ViewBag.AppConfig.GroupDomain), forceRefresh);

            var vm = new GroupDetailViewModel()
            {
                Group = groupObj
            };

            vm.VueData = _vueParser.ParseData(vm);

            return View(vm);
        }

        [HttpGet("add")]
        [PermissionAuthorize(Permissions.CreateGroup)]
        public IActionResult Add()
        {
            return View();
        }
    }
}

src/web/Views/Groups/Add.cshtml
@{
    ViewData["Title"] = "Create New Group";
}
@section breadcrumbs {
    <li class="breadcrumb-item">Create New Group</li>
}
<h2>Create New Group</h2>

<div class="mt-2 row">
    <div class="col-lg-5 col-md-8">
        <div id="js-vue-app"
             data-endpoint="@Url.Action("AddGroup", "GroupsApi")"
             data-editendpoint="@Url.Action("Index", "Groups", new { group = "-999" })"
             data-domain="@ViewBag.AppConfig.GroupDomain"></div>
    </div>
</div>



@section mastercss {

    <environment excludes="Development">
        <link asp-href-include="~/assets/pages.groups.add.*.css" rel="stylesheet" media="all" />
    </environment>
}

@section masterjs{
    <environment exclude="Development">
        <script defer type="module" asp-src-include="~/assets/pages.groups.add.*.js"></script>
    </environment>

    <environment include="Development">
        <script defer type="module" src="~/pages/groups/add/index.js"></script>
    </environment>
}

src/web/Views/Groups/Index.cshtml
@model GroupDetailViewModel
@{
    ViewData["Title"] = Model.Group.EmailKey;
}

@section breadcrumbs {
<li class="breadcrumb-item">@Model.Group.EmailKey</li>
}
<script id="js-app-initial-data" type="application/json">
    @Model.VueDataToJson()
</script>

<h2>Settings - @Model.Group.Name (@Model.Group.Email)</h2>


<div id="js-vue-app"
     data-endpoint="@Url.Action("Get", "GroupsApi", new { group = ViewContext.RouteData.Values["group"].ToString() })"
     data-session="@Url.Content("~/session")"></div>


@section mastercss {

    <environment excludes="Development">
        <link asp-href-include="~/assets/pages.groups.index.*.css" rel="stylesheet" media="all" />
    </environment>
}

@section masterjs{
    <environment exclude="Development">
        <script defer type="module" asp-src-include="~/assets/pages.groups.index.*.js"></script>
    </environment>

    <environment include="Development">
        <script defer type="module" src="~/pages/groups/index/index.js"></script>
    </environment>
}